### ISSUE TITLE
Ionic View Won't Update

### ISSUE THREAD

**Issue by jfkoch** [driftyco/ionic-view-issues#80] opened 2015-04-17 06:54 UTC
After I push changes to ionic the Ionic View app shows an update but what is downloaded is an old version of the app.

**Comment by tlancina** [comment] 2015-04-17 15:21
If the updated changes won't show even after you restart the app, try setting app_id in your ionic.project file to "" before running `ionic upload` to upload a new project.

Closing as a duplicate of #10.

**Closed by tlancina** 2015-04-17 15:21 UTC
