### ISSUE TITLE
Camera Plugin does not work with the View App

### ISSUE THREAD

**Issue by svigano** [driftyco/ionic-view-issues#79] opened 2015-04-16 00:48 UTC
Do you guys have a timeframe to support the camera plugin ?

**Comment by tlancina** [comment] 2015-04-16 04:18
The camera plugin is available in View already (or at least it should be!).

**Comment by svigano** [comment] 2015-04-16 13:19
Thanks!

I probably got confused since the Blog
http://blog.ionic.io/view-app-is-alive/ didn't mentioned the camera
support.

**Comment by patrickse** [comment] 2015-04-17 11:07
I just tried the camera plugin and it looks like it´s failing for me too.

**Comment by tlancina** [comment] 2015-04-17 12:04
Hmm, Android or iOS?

**Comment by patrickse** [comment] 2015-04-17 13:23
iOS

**Comment by tlancina** [comment] 2015-04-17 13:58
Works fine for me on an iPhone 5, can you guys do the following:

```
ionic start cameraTest http://codepen.io/tlancina/pen/bdbpLb
cd cameraTest
ionic upload
```
And test it out on View? 

Also please provide:
  - the device
  - the code you are using

**Comment by svigano** [comment] 2015-04-17 14:23
I tried your test app.

When I run it on my IPhone 5 in the Ionic View App, after I press the Take Picture button the phone brings up the camera UI but I can see only a black screen. If I tried to take a picture nothing happen. if I press cancel I get this alarm: Index.html Failed because: has no access to assets.

I'm seeing the same behavior with my code. 

Running IOS 8.1.3

**Comment by tlancina** [comment] 2015-04-17 14:45
Looks like a weird iOS bug, here's the relevant Cordova issue: https://issues.apache.org/jira/browse/CB-7641.  I can't reproduce on a 5s running 7.1 or a 6+ with 8.3, but you definitely are not alone.

I'm going to close this for now, as I don't think there's much we can do, but try updating to 8.3 and see if that helps.  Also it looks like camera has come out with version 1.0, so I'll update it in the next View release.

**Closed by tlancina** 2015-04-17 14:45 UTC

**Comment by svigano** [comment] 2015-04-17 19:10
Ok Tim.

Thanks for your help! I'll try to update to 8.3 over the weekend.

Simone
