### ISSUE TITLE
StatusBar plugin not working in Ionic View?

### ISSUE THREAD

**Issue by btober** [driftyco/ionic-view-issues#35] opened 2015-03-02 22:07 UTC
I can use the Ionic Weather sample as an example (https://github.com/driftyco/ionic-weather). If I build this and emulate it in the iOS Simulator, the status bar is hidden. When I upload it and try to view it using Ionic View, the status bar is still present. Any ideas? It seems like the Status Bar plugin just isn't working with Ionic View, but I haven't seen any other complaints about this.

**Comment by qnodesign** [comment] 2015-03-06 16:11
I also have the same issue. I added the styleLightContent(); and on simulator works well, but not in the ionic view.

**Comment by tlancina** [comment] 2015-03-06 20:32
This should work, I've used it myself.  Try wrapping the statusBar call in
a $timeout/setTimeout, it's possible that View hasn't initialized yet.

**Comment by btober** [comment] 2015-03-07 15:01
That doesn't work for me, unfortunately. Using the blank template (and without making any other changes), the following code...

    alert("test");
    if(window.StatusBar) {
	  alert("test2");
      StatusBar.hide();
    }

...results in an alert with test appearing, but not one with test2. Wrapping the whole if block, or just the StatusBar.hide() line, in a timeout does nothing.

Again, this code works fine in the iOS Simulator. Can you share your code that you know to work in Ionic View?

**Comment by tlancina** [comment] 2015-03-07 16:48
Hmm interesting, the code I tested was to help someone who wanted to change
the statusbar color of a black app:

```
StatusBar.overlaysWebView(false);
StatusBar.styleBlackTranslucent();
StatusBar.backgroundColorByName('black');
```

Which worked great in a small $timeout.

I wonder if .hide() is affected by the setting "View controller-based
status bar appearance" = NO, which View has set.

**Comment by qnodesign** [comment] 2015-03-07 19:49
For me the second code was working properly:
looks like the following in the app.js

angular.module('starter', ['ionic', 'starter.controllers'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    
    setTimeout(function() {
      if (window.StatusBar) {
        StatusBar.styleBlackTranslucent();
        StatusBar.backgroundColorByName('black');
      }
    }, 300); 
    
  });
})

so in my case the statusbar is white on a black bg in ion-view.
Thanks for the help Tim!

**Comment by btober** [comment] 2015-03-07 20:56
So perhaps it is related specifically to showing and hiding the status bar?

**Comment by tlancina** [comment] 2015-03-07 21:19
That is certainly possible, but considering your second alert didn't fire,
it seems that StatusBar isn't on window for you. I'm not sure what the
issue could be since you said you were using a blank starter. Maybe try
reinstalling the StatusBar plugin?

**Comment by tlancina** [comment] 2015-03-07 21:20
Hah derp, you can't reinstall the plugin on View! I'm honestly not sure
what could be going on, the second alert not firing is strange.

**Comment by tlancina** [comment] 2015-03-09 18:57
Hey closing this as I had no issue getting the statusbar to hide, although I will say a couple times it took a pretty long time to init - I'll see if there's any way to bring that time down.  Also I think it would be worthwhile to expose something like ionic.Platform.ready for View so people don't have to wrap their code in a setTimeout/$timeout to get it to work.

**Closed by tlancina** 2015-03-09 18:57 UTC

**Comment by superKalo** [comment] 2015-06-03 14:08
Hey, I have the same issue. I tried to set a set timeout - it does not work on my side :( When I alert window.StatusBar I get `undefined` on a real device after a 300ms timeout. Any other suggestions?

```
myApp.run(['$ionicPlatform', function($ionicPlatform){
    $ionicPlatform.ready(function() {
        setTimeout(function(){
            alert(window.StatusBar);
            if (window.StatusBar) {
                StatusBar.overlaysWebView(false);
                StatusBar.styleBlackTranslucent();
                StatusBar.backgroundColorByName('black');
            }
        }, 300);
    });
}]);
```

**Comment by armensg** [comment] 2016-01-14 09:58
This doesn't work for me either. I have  black bg and want the status bar to be white.
I dont see the StatusBar plugin in this page

http://docs.ionic.io/v1.0/docs/view-usage

**Comment by jackvial** [comment] 2016-04-19 20:20
I'm pretty sure the status bar plugin is not supported by Ionic view. The plugin works fine on my device but not in Ionic view. Like @armensg said, the plugin is not like as being supported.

**Comment by dwinnbrown** [comment] 2016-10-02 20:01
Did anyone come to a conclusion on this? Still behaving in the same way for me but if I build to the simulator it works fine as expected...

**Comment by tlancina** [comment] 2016-10-06 15:40
@dwinnbrown are you on Android or iOS?

**Comment by dwinnbrown** [comment] 2016-10-06 15:41
It’s the iOS version - haven’t tried the android viewer.

Thanks

Dylan Winn-Brown

http://winn-brown.co.uk <http://winn-brown.co.uk/>

**Comment by tlancina** [comment] 2016-10-06 15:59
@dwinnbrown ok thanks, I noticed some issues with Android, but iOS should be working.  With the latest version of View (1.1.1 on iOS), make sure to wrap any plugin code you run (like StatusBar) with `$ionicPlatform.ready` so that plugins will have initialized.

If it's still not working for you, if you could open a new issue with the device type, iOS version and steps to reproduce I can take a look, thanks!

**Comment by dwinnbrown** [comment] 2016-10-06 16:49
Ok will take another look

Thanks
