### ISSUE TITLE
A small grey rectangle appears in view

### ISSUE THREAD

**Issue by bkrajendra** [driftyco/ionic-view-issues#177] opened 2016-07-31 05:02 UTC
A small gray rectangle is always visible in all ionic views at top left corner below navicon.
![ionic](https://cloud.githubusercontent.com/assets/994083/17274657/f705b1f4-5709-11e6-8d79-49ac357a53ec.PNG)

How to get rid of this issue.

**Comment by pavelety** [comment] 2016-08-27 10:36
Ionic, v1.3.1
+1
I can see it in app on device and in emulator in Chrome.
When I disable and enable any style in developer console in Chrome it dissapears. But when I toggle menu it appears again.
![image](https://cloud.githubusercontent.com/assets/1104626/18026832/2f1648e0-6c5b-11e6-95cf-987c870859d1.png)

**Comment by tlancina** [comment] 2016-08-30 13:50
Closing as a duplicate of https://github.com/driftyco/ionic/issues/6416 since it's not a View issue.

**Closed by tlancina** 2016-08-30 13:50 UTC
