### ISSUE TITLE
How do we refresh?

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-view-issues#7] opened 2015-01-15 16:06 UTC
I loaded Ionic View on my device, logged in, and it correctly said I had no apps yet. I made an app at the command line, uploaded it, and... now what? I don't see a refresh option.

**Comment by cfjedimaster** [comment] 2015-01-15 16:06
Hmm. I killed the app and restarted - still no apps.

**Comment by cfjedimaster** [comment] 2015-01-15 16:33
I've also tried logging off and on, no luck.

**Comment by mlynch** [comment] 2015-01-15 16:34
Try pulling to refresh on the apps list page, does that work?

On Thu, Jan 15, 2015 at 10:33 AM, Raymond Camden <notifications@github.com>
wrote:

> I've also tried logging off and on, no luck.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/7#issuecomment-70114417>
> .
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by cfjedimaster** [comment] 2015-01-15 16:40
I don't have an app list page. Just a page saying I don't have any apps and
I can get a sample or upload my own. That one just lets to an instruction
page.

On Thu, Jan 15, 2015 at 10:34 AM, Max Lynch <notifications@github.com>
wrote:

> Try pulling to refresh on the apps list page, does that work?
>
> On Thu, Jan 15, 2015 at 10:33 AM, Raymond Camden <notifications@github.com>
>
> wrote:
>
> > I've also tried logging off and on, no luck.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/driftyco/ionic-view-issues/issues/7#issuecomment-70114417>
>
> > .
> >
>
>
>
> --
> Max Lynch
> CEO and Co-founder
> http://ionicframework.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/7#issuecomment-70114632>
> .
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by mlynch** [comment] 2015-01-15 16:59
Got it. cc @tlancina

**Comment by tlancina** [comment] 2015-01-15 17:01
@cfjedimaster I'm not so sure it's even uploading, the CLI seems to be failing silently for some people and we're trying to figure out what the issue is.  

When you run `ionic upload` does it display a success message with the app id afterwards?

**Comment by cfjedimaster** [comment] 2015-01-15 19:28
Nope.

**Comment by timothyha** [comment] 2015-01-15 20:41
@cfjedimaster I also didn't have app id at first upload, but it worked on a second time for me.  You have to wait until you get "Successfully uploaded", then the id you see should be used in "ionic view".  I am going to try @tlancina's app now :)

**Comment by tlancina** [comment] 2015-01-15 21:35
@cfjedimaster would you mind posting the output of `ionic info` when you get a chance please?

**Comment by cfjedimaster** [comment] 2015-01-15 21:35
Uploading a second time worked and the app auto refreshed to show it. I think you can close this - but maybe consider documenting someplace the 'pull to refresh' behavior.

**Comment by tlancina** [comment] 2015-01-15 21:40
@cfjedimaster great! Closing this for now, but yes we have some work to do on making the process more clear.

**Closed by tlancina** 2015-01-15 21:40 UTC
