### ISSUE TITLE
Ionic adds blank space below the header when using ionic uplaod

### ISSUE THREAD

**Issue by strenev** [driftyco/ionic-view-issues#119] opened 2015-06-03 20:26 UTC
Hello, when I try to upload my app to Ionic View, the consequence is that the html or css somehow brakes and blank space appears below the header.

**Comment by simplesmiler** [comment] 2015-06-03 20:52
May be related to https://github.com/driftyco/ionic-cli/issues/452

**Comment by bradmartin** [comment] 2015-06-03 22:32
@simplesmiler correct. I just posted a work around that works for me to that issue https://github.com/driftyco/ionic-cli/issues/452

**Comment by tlancina** [comment] 2015-08-16 04:21
Should have been fixed with https://github.com/driftyco/ionic-app-lib/commit/b757d3866176d531de7bb6806bbeb29882f6010a.  If not, feel free to reopen https://github.com/driftyco/ionic-cli/issues/452 with steps to reproduce, thanks!

**Closed by tlancina** 2015-08-16 04:21 UTC
