### ISSUE TITLE
"View app" disabled

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-view-issues#84] opened 2015-04-22 14:11 UTC
I've uploaded an app and can see it in Ionic View, but when I select it, "View app" is disabled. I'm sure I did something wrong, but I've got no idea why I can't view the app.

**Comment by cfjedimaster** [comment] 2015-04-22 14:12
Ok, I see from here, http://forum.ionicframework.com/t/solved-unable-to-click-on-the-view-app-button-for-uploaded-project-in-ionic-view-android-app/20263, that you need to download first. This *really* needs to be made obvious in the app ui.

**Comment by tlancina** [comment] 2015-04-22 15:26
Yeah it's a little weird. Honestly the first button in the list should say Download, and then change to View once it has downloaded, instead of Download turning into Sync once you've downloaded.

**Comment by cfjedimaster** [comment] 2015-04-22 15:27
Maybe Download on top, and below it where view would be:

"You can view once downloaded."

**Comment by tlancina** [comment] 2015-04-22 15:59
Oh I was thinking have them be one and the same. Right now Download changes to Sync once you've downloaded the app files, so instead there would be just be a disabled Sync option as the third button and the first button would be Download, which would switch to View once downloaded.  How does that sound? I feel like Download -> View instead of Download -> Sync, makes more sense for the reason you opened this issue (no one is going to be thrown that Sync is disabled, but it's weird that View is).

**Comment by cfjedimaster** [comment] 2015-04-22 16:06
Sounds good to me.

On Wed, Apr 22, 2015 at 8:59 AM, Tim Lancina <notifications@github.com>
wrote:

> Oh I was thinking have them be one and the same. Right now Download
> changes to Sync once you've downloaded the app files, so instead there
> would be just be a disabled Sync option as the third button and the first
> button would be Download, which would switch to View once downloaded. How
> does that sound? I feel like Download -> View instead of Download -> Sync,
> makes more sense for the reason you opened this issue (no one is going to
> be thrown that Sync is disabled, but it's weird that View is).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/84#issuecomment-95246040>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by davidsneal** [comment] 2015-05-14 08:48
:+1:

**Comment by techsin** [comment] 2015-05-15 14:51
i thought download meant download apk or something.

**Comment by w-** [comment] 2015-05-16 05:11
ROFL. ...better explanation in the UI definitely needed.

**Comment by tpalmer75** [comment] 2015-06-08 02:47
Had the exact same issue.

**Comment by simpixelated** [comment] 2015-06-10 18:42
@tlancina What about "Download and View" -> View? FYI had to come here to figure out how to open the app so it's definitely an issue.

**Comment by tlancina** [comment] 2015-06-10 18:54
This has been updated in iOS already and will be in the next Android update.

**Comment by EIrwin** [comment] 2015-07-18 17:28
Yeah, this is very confusing. If an update for this is not going to be a priority, then the documentation explaining the process for uploading or using Ionic view should explain this very clearly.

**Comment by natsn** [comment] 2015-08-04 23:15
Had to come here to figure this out! I like the "Download & View" solution. Maybe with the payload size next to it.

**Comment by Oliver84** [comment] 2015-09-13 20:25
lol, +1. I had no idea what was wrong...

**Comment by wmyers** [comment] 2015-10-13 04:40
This is still confusing people, glad I found this page

**Comment by nikolasleblanc** [comment] 2015-10-19 21:04
+1

**Comment by jmsherry** [comment] 2015-11-17 05:24
Yup! Needs making clearer...

**Comment by Requiescat** [comment] 2015-12-03 03:33
+1

**Comment by mixpack** [comment] 2016-01-11 15:35
+1

**Comment by topazdecimal** [comment] 2016-05-05 08:15
It hasn't changed, it's over a year now.

**Comment by anupshinde** [comment] 2016-07-30 07:52
First time trying my hands on ionic. The "Download Files" option isn't intuitive - Felt like it was an option to download the source code. 
Had to see this thread to get started. May be that can be renamed to "Download App". Or since IonicView knows the app isn't downloaded the View could say "Download and View"

**Comment by PrithiviRajG** [comment] 2016-09-01 12:23
FYI, still the issue is there.

**Comment by HorseFly** [comment] 2016-09-15 02:50
Mine is completing the Download Files sync and the View App is still disabled.

**Comment by tlancina** [comment] 2016-10-05 18:40
Closing this as it's been updated in both the latest Android and iOS versions. As always, let us know if you're still having problems, thanks!

**Closed by tlancina** 2016-10-05 18:40 UTC
